fc_normalization:
  input:
    train: "train.csv"
    test: "test.csv"
  output:
    train: "train_normalized.csv"
    test: "test_normalized.csv"
  format:
    sep: ","
    label: "y"
  split:
    mode: directory
    dir: data
  normalization: variance